# Generated by Django 4.0.5 on 2022-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=12)),
                ('password', models.IntegerField(max_length=12)),
            ],
        ),
    ]
